apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app-deployment
  name: go-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: go-app-deployment
    spec:
      containers:
      - image: mahdi0188/go-promethus-kpis
        name: go-promethus-kpis

status: {}
