apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-app-deployment

  annotations: 
    prometheus: scrape
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000" 
    prometheus.io/path: "/prometheus"  
  name: go-app-deployment
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  selector:
    app: go-app-deployment
status:
  loadBalancer: {}
